# Generated by Django 2.0.4 on 2019-02-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='text_plain',
        ),
        migrations.AddField(
            model_name='save',
            name='user',
            field=models.CharField(default='Gabriel', max_length=100),
            preserve_default=False,
        ),
    ]
