# Generated by Django 2.0.4 on 2019-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190209_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='firm',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
