# Generated by Django 2.0.4 on 2019-02-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_save_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='firm',
            field=models.CharField(max_length=100000),
        ),
    ]
